gText_Birch_Welcome::
	.string "Ara ara!\p"
	.string "Welcome to POKéMON BLAZEBORN!\p"
	.string "My name is MEL.\p$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "'MAIN SPEECH HERE'\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Which skin do\n"
	.string "you want?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON BLAZEBORN "
	.string "where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
